### ISSUE TITLE
Add possibility to not scroll from the first step to the last step if we didn't came from the last step

### ISSUE THREAD

**Issue by yelkamel** [wjuniorgit/loop_page_view#18]
Hello,

Thanks for you package, I use it for a funnel scrolling like TikTok. 

When we are on the last step we want to be able to scroll to the first step so that OK.

The problem is initialy when we are at the first step with this package, we can directly go to the last step...

If there is a way to change that thanks.

**Comment by wjuniorgit** [comment]
* Create `LoopActivationMode` to control when loop starts. You have to create your own custom instance of `LoopPageViewController` to set which `LoopActivationMode` it uses. By default the value is set to `immediate`.

`LoopActivationMode` is an enum that represents the different modes of activating the infinite loop in the `LoopPageView`.

The modes are:
* `immediate`: Infinite loop is enabled from the start. As soon as the `LoopPageView` is loaded, the user can scroll infinitely in both directions.
* `afterFirstLoop`: The infinite loop is only enabled after the first loop through all pages. Initially, the user can scroll through the pages in normal sequence. Once the user reaches the end and loops back to the first page, infinite scrolling is enabled.
* `forwardOnly`: Infinite scrolling is only enabled in the forward direction. The user can scroll forward through the pages indefinitely, but cannot scroll backwards past the first page.

```
enum LoopActivationMode {
  immediate,
  afterFirstLoop,
  forwardOnly,
}
```
