### ISSUE TITLE
Feature Request: AnimateToPage without showing(creating) the middle Pages

### ISSUE THREAD

**Issue by aytunch** [wjuniorgit/loop_page_view#2]
I see that lots of people want to `animateToPage` but without showing the pages in the middle. Lets say we have 10 pages [0...9]. And we want to `AnimateToPage` from `page3` to `page6`. Flutter shows `page4, page5` during the animation. For most of the cases this is an unwanted behavior and brings Jank to the animation. Some of the middle pages might be disposed before and their `initState()` might run and they might even make an unnecessary network calls or heavy business. 

The "nice behavior" would be animating a page change from `page3` to `page6` as if they were neighbors. And we would need an optional direction argument to tell the controller if `page6` is on the left or right side of `page3`. Similar to what you did in `loop_page_view`

I saw your code and how clean you handled the Loop case 👍  I think, what I ask is similar to what you did here. 
Please write if you are interested and would consider making a PR for this use case. I can try to give a hand if needed:)

This might be maybe more suited inside of a new Package. You will be the judge of that:)

Also a quick question: for `loop_page_view`, when there is only 1 item, will it still scroll from/to itself? Can we optionally enable disable 1 item scrolling case?

**Comment by wjuniorgit** [comment]
Hi aytunch, thank you for your feature request and your comments on the package. 
It is really a nice idea to have a method that avoids building the pages in the middle while animating the change. 
I have created a new method on LoopPageController (animateJumpToPage) in wich I tried to implement the "nice behavior" that you described, but without the optional direction argument. It animates to the "closer" page inside the loop.

Regarding your quick question, you can disable scroll when there is only one item by setting the physics on LoopPageView as NeverScrollableScrollPhysics() just as you would with a default PageView.
