### ISSUE TITLE
[WEB] [DESKTOP] Jumping while scrolling between the loop pages (first and last page)

### ISSUE THREAD

**Issue by behnamsattar** [wjuniorgit/loop_page_view#6]
I have been seeing jumping when I swipe between the last and first page on my desktop Chrome and Safari. It might be related to scrolling using two fingers on the desktop.

Other things to note:
* I do not experience this on the iOS simulator on my machine. It uses tap and drag scrolling.
* I'm using the HTML renderer. I have not tested this on the CanvasKit renderer.

Just run the example application on desktop Chrome or Safari to reproduce this.

**Comment by wjuniorgit** [comment]
Thanks for the feedback, I have never actually tried to run this Widget in a browser. I will see to it.
