### ISSUE TITLE
Use the Listenable interface for the LoopPageController

### ISSUE THREAD

**Issue by behnamsattar** [wjuniorgit/loop_page_view#7]
The LoopPageController has the methods needed to be a Listenable, but it doesn't explicitly implement this interface. As a result, users cannot use a LoopPageController where a Listenable is expected.

I usually use an AnimatedBuilder() with a PageViewController or a ScrollController as the animation in my specific use case. Because they all implement the Listenable interface, it works great, and I can animate things based on the page value on my regular PageViewController.

We need to add the Listenable interface to the LoopPageController, which should be simple and easy.

**Comment by behnamsattar** [comment]
For now I'm using this workaround:

```dart
class ListenableLoopPageController extends LoopPageController implements Listenable {}
```

**Comment by wjuniorgit** [comment]
I will check this out and add it to the lib.
