### ISSUE TITLE
RangeError(index): Index out of range

### ISSUE THREAD

**Issue by Twila** [wjuniorgit/loop_page_view#8]
hello, I have come up with a confusing problem when using the loop_page_view in my project. I get a word from a string set same as you, when I scroll the page. However, the code will crush once I hot reload the code without any change. I wonder if I misundestand the usage of the  view pager since I am a freshmen of flutter. Hope for your help><
PS: My flutter version is 2.5.2
```
class LoopViewPage extends StatefulWidget {
  LoopViewPage({Key? key}) : super(key: key);

  @override
  _LoopViewState createState() => _LoopViewState();
}

class _LoopViewState extends State<LoopViewPage>{
  final Set<String> pageList = {'first', 'second', 'third'};

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: LoopPageView.builder(
            itemCount: 3,
            itemBuilder: (_, index) {
              return Container(
                decoration: const BoxDecoration(
                  image: DecorationImage(
                    image: AssetImage("images/img_bg.png"),
                    fit: BoxFit.cover,
                  ),
                ),
                child: Center(
                  child: Text(
                    pageList.elementAt(index),
                    style: TextStyle(fontSize: 20, color: Colors.white),
                  ),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

https://user-images.githubusercontent.com/17776731/155096368-c4167376-b480-4459-b201-9ea7905f4c09.mp4

**Comment by wjuniorgit** [comment]
Thanks for the feedback, your code is very simple, I don't think there is anything wrong with it.
Maybe the way LoopPageViewController is working right now is not really the best when you want to hot reload.
I will try to reproduce this issue and if I am able to I will get it fixed.
